using SolaceWeather.Core;
namespace SolaceWeather.Core.Tests;

public class RomanceTests
{
    [Fact] public void DatingRequiresTimeTalkAndVariedActivities() { var s = new RomanceSaveState(); RomanceRules.Contact(s, "Abigail", 1); RomanceRules.ExpressInterest(s, "Abigail", 1); for (int d = 1; d <= 12; d++) { RomanceRules.Talk(s, "Abigail", d); if (d <= 4) RomanceRules.RecordCompletedActivity(s, "Abigail", d, d % 2 == 0 ? "walk" : "picnic"); } Assert.False(RomanceRules.StartDating(s, "Abigail", 28)); Assert.True(RomanceRules.StartDating(s, "Abigail", 29)); }
    [Fact] public void DuplicateDayCannotFarmProgress() { var s = new RomanceSaveState(); Assert.True(RomanceRules.RecordCompletedActivity(s, "Leah", 1, "walk")); Assert.False(RomanceRules.RecordCompletedActivity(s, "Leah", 1, "picnic")); Assert.Equal(1, s.Characters["Leah"].CompletedActivities); }
    [Fact] public void SecondIncidentMustFollowDeliveredWarning() { var s = new RomanceSaveState(); RomanceRules.ImportPartner(s, "Leah", 1, false); RomanceRules.Reaffirm(s, "Leah", 1); RomanceRules.RecordIncident(s, "one", "Abigail", 2, "kiss"); RomanceRules.LearnIncident(s, "one", "Leah", 2, "witness"); Assert.True(s.Characters["Leah"].InConflict); RomanceRules.DeliverWarning(s, "Leah", 2); RomanceRules.RecordIncident(s, "two", "Abigail", 3, "kiss"); RomanceRules.LearnIncident(s, "two", "Leah", 3, "witness"); Assert.Equal(17, s.Characters["Leah"].SeparationUntilDay); RomanceRules.AdvanceDay(s, 17); Assert.Equal("breakup", s.Characters["Leah"].PendingTransition); }
    [Fact] public void ImportedPartnerNeedsReaffirmation() { var s = new RomanceSaveState(); RomanceRules.ImportPartner(s, "Leah", 1, true); RomanceRules.RecordIncident(s, "one", "Abigail", 2, "kiss"); RomanceRules.LearnIncident(s, "one", "Leah", 2, "witness"); Assert.False(s.Characters["Leah"].InConflict); Assert.Null(s.Characters["Leah"].DatingSinceDay); }
    [Fact] public void BookingIsGlobalAndNoShowIsNotBetrayal() { var s = new RomanceSaveState(); Assert.True(RomanceRules.Book(s, "Leah", 2, 600, 1, 600, "walk")); Assert.False(RomanceRules.Book(s, "Abigail", 2, 600, 1, 600, "walk")); RomanceRules.AdvanceBooking(s, 2, 631); Assert.Null(s.Booking); Assert.Equal(1, s.Characters["Leah"].NoShows); Assert.False(s.Characters["Leah"].InConflict); RomanceRules.AdvanceBooking(s, 2, 700); Assert.Equal(1, s.Characters["Leah"].NoShows); }
    [Fact] public void InvalidSaveFailsClosed() { var s = new RomanceSaveState { Version = 999 }; Assert.False(RomanceRules.Contact(s, "Leah", 1)); Assert.False(s.IsValid()); }
    [Fact] public void ElapsedTimeDoesNotCompleteActivities() { var s = new RomanceSaveState(); RomanceRules.Book(s, "Leah", 1, 600, 1, 500, "walk"); Assert.True(RomanceRules.Arrive(s, 1, 600)); RomanceRules.AdvanceBooking(s, 1, 700); Assert.Equal(0, s.Characters["Leah"].CompletedActivities); Assert.False(RomanceRules.RecordActivitySegment(s, 1, 610)); Assert.True(RomanceRules.RecordActivitySegment(s, 1, 620)); Assert.True(RomanceRules.RecordActivitySegment(s, 1, 640)); Assert.True(RomanceRules.RecordActivitySegment(s, 1, 660)); Assert.Null(s.Booking); Assert.Equal(1, s.Characters["Leah"].CompletedActivities); }
    [Fact] public void EarlierUnknownIncidentCannotBecomeSecondStrike() { var s = new RomanceSaveState(); RomanceRules.ImportPartner(s, "Leah", 1, false); RomanceRules.Reaffirm(s, "Leah", 1); RomanceRules.RecordIncident(s, "a", "Abigail", 2, "kiss"); RomanceRules.RecordIncident(s, "b", "Abigail", 2, "kiss"); RomanceRules.LearnIncident(s, "a", "Leah", 2, "witness"); RomanceRules.DeliverWarning(s, "Leah", 2); RomanceRules.LearnIncident(s, "b", "Leah", 3, "Abigail", 1); Assert.Null(s.Characters["Leah"].SeparationUntilDay); Assert.False(RomanceRules.LearnIncident(s, "a", "Leah", 3, "witness")); }
    [Fact] public void RepairRequiresAcknowledgementTwoDaysAndSevenQuietDays() { var s = new RomanceSaveState(); RomanceRules.ImportPartner(s, "Leah", 1, false); RomanceRules.Reaffirm(s, "Leah", 1); RomanceRules.RecordIncident(s, "a", "Abigail", 2, "kiss"); RomanceRules.LearnIncident(s, "a", "Leah", 2, "witness"); Assert.False(RomanceRules.RecordCompletedActivity(s, "Leah", 2, "walk", repair: true)); RomanceRules.AcknowledgeConflict(s, "Leah", 2); RomanceRules.RecordCompletedActivity(s, "Leah", 3, "walk", repair: true); Assert.False(RomanceRules.RecordCompletedActivity(s, "Leah", 3, "picnic", repair: true)); RomanceRules.RecordCompletedActivity(s, "Leah", 4, "walk", repair: true); RomanceRules.AdvanceDay(s, 8); Assert.True(s.Characters["Leah"].InConflict); RomanceRules.AdvanceDay(s, 9); Assert.False(s.Characters["Leah"].InConflict); }
    [Fact] public void ReportsHaveHopAgeAndSenderDailyLimits() { var s = new RomanceSaveState(); RomanceRules.RecordIncident(s, "a", "Abigail", 1, "kiss"); RomanceRules.RecordIncident(s, "b", "Abigail", 1, "kiss"); RomanceRules.LearnIncident(s, "a", "Sam", 1, "witness"); RomanceRules.LearnIncident(s, "b", "Sam", 1, "witness"); Assert.True(RomanceRules.SendReport(s, "Sam", "Leah", "a", 1)); Assert.False(RomanceRules.SendReport(s, "Sam", "Penny", "b", 1)); Assert.True(RomanceRules.SendReport(s, "Leah", "Penny", "a", 1)); Assert.False(RomanceRules.SendReport(s, "Penny", "Maru", "a", 1)); Assert.False(RomanceRules.SendReport(s, "Sam", "Maru", "b", 9)); }
    [Fact] public void HistoryTrimmingNeverLosesProgressOrPermitsOldDayCredit() { var s = new RomanceSaveState(); for (int d = 1; d <= 300; d++) Assert.True(RomanceRules.RecordCompletedActivity(s, "Leah", d, "walk")); Assert.Equal(300, s.Characters["Leah"].CompletedActivities); Assert.Equal(256, s.History.Count); Assert.False(RomanceRules.RecordCompletedActivity(s, "Leah", 1, "walk")); }
    [Fact] public void NonCandidateWitnessPreservesOriginalSource() { var s = new RomanceSaveState(); RomanceRules.RecordIncident(s, "a", "Leah", 1, "flirt"); Assert.True(RomanceRules.LearnIncident(s, "a", "Robin", 1, "witness")); Assert.True(RomanceRules.SendReport(s, "Robin", "Pierre", "a", 1)); Assert.True(RomanceRules.SendReport(s, "Pierre", "Abigail", "a", 1)); Assert.Equal("Robin", s.Knowledge.Last().OriginalEyewitness); Assert.Equal("Pierre", s.Knowledge.Last().Source); Assert.False(s.Characters.ContainsKey("Robin")); Assert.True(s.IsValid()); }
    [Fact] public void IncidentRetentionDoesNotDisableLaterConsequences() { var s = new RomanceSaveState(); for (int day = 1; day <= 520; day++) { Assert.True(RomanceRules.AdvanceDay(s, day)); Assert.True(RomanceRules.RecordIncident(s, $"event-{day}", "Leah", day, "flirt")); } Assert.InRange(s.Incidents.Count, 1, 8); Assert.Equal(521, s.NextIncidentSequence); Assert.False(RomanceRules.RecordIncident(s, "event-1", "Leah", 1, "flirt")); }
    [Fact] public void TransitionStartsFreshCourtshipAndKeepsMemories() { var s = new RomanceSaveState(); RomanceRules.ImportPartner(s, "Leah", 1, true); RomanceRules.Reaffirm(s, "Leah", 1); RomanceRules.RecordCompletedActivity(s, "Leah", 1, "walk", true); var c = s.Characters["Leah"]; c.InConflict = true; c.PendingTransition = "divorce"; Assert.True(RomanceRules.CompleteTransition(s, "Leah", 2)); Assert.False(c.IsDating); Assert.Equal(0, c.CompletedActivities); Assert.Equal(0, c.RomanticDates); Assert.Empty(c.ActivityTypes); Assert.NotEmpty(s.History); }
    [Fact] public void EstablishedAndProposalUseDatingClockAndRomanticDates() { var s = new RomanceSaveState(); RomanceRules.ImportPartner(s, "Leah", 1, false); RomanceRules.Reaffirm(s, "Leah", 1); for (int d = 1; d <= 8; d++) RomanceRules.RecordCompletedActivity(s, "Leah", d, "walk", true); Assert.False(s.GetJourney("Leah", 28).Established); Assert.True(s.GetJourney("Leah", 29).Established); Assert.False(s.GetJourney("Leah", 56).CanPropose); Assert.True(s.GetJourney("Leah", 57).CanPropose); s.Characters["Leah"].IsEngaged = true; Assert.False(s.GetJourney("Leah", 57).CanPropose); }
    [Fact]
    public void TransitionClearsEveryConflictOverlay()
    {
        var state = new RomanceSaveState();
        RomanceRules.ImportPartner(state, "Leah", 1, true);
        var character = state.Characters["Leah"];
        character.InConflict = true;
        character.SeparationUntilDay = 14;
        character.PendingTransition = "divorce";
        character.LastViolationDay = 1;
        character.LastViolationSequence = 5;
        character.WarningIncidentSequence = 5;
        Assert.True(RomanceRules.CompleteTransition(state, "Leah", 2));
        Assert.True(state.IsValid());
        Assert.False(character.NeedsReaffirmation);
        Assert.Null(character.SeparationUntilDay);
        Assert.Null(character.LastViolationDay);
        Assert.Equal(0, character.WarningIncidentSequence);
        Assert.Equal(0, character.LastViolationSequence);
        Assert.Equal("friendship", state.GetJourney("Leah", 2).Stage);
    }
}
